name: Test Job
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test crawling
        run: |
          python app.py -c crawl -i https://elizabeth.co.id/ elizabeth.txt

      - name: File checking
        run: |
          wc -l elizabeth.txt
          head -n 10 elizabeth.txt > test.txt
          cat test.txt

      - name: Test scraping
        run: |
          python app.py -c scrape -i test.txt test.json
          cat test.json | jq
          
